TOKEN = ''
COMMAND_PREFIX = '!'

# VHU Portal
VHU_USER_NAME = ''
VHU_PASSWORD = ''

# Shopee Account
SHOPEE_USER_NAME = ''
SHOPEE_PASSWORD = ''

#PATH CHROME DRIVER
PATH_CHROME_DRIVER = r'C:\Users\BRAVO\py\auto\chromedriver.exe'

#CHATGPT ACCOUNT
EMAIL_CHATGPT = ''
PASSWORD_CHATGPT = ''

#MAIN CHANNEL
CHANNEL_ID_GENERAL = ""

#UPDATE TEST SCORE CHANNEL
CHANNEL_VHU_SCORE = ""

#Anime News Channel
CHANNEL_ANIME_NEWS = ""