TOKEN = ''
COMMAND_PREFIX = '!'

# VHU Portal
VHU_USER_NAME = ''
VHU_PASSWORD = ''

# Shopee Account
SHOPEE_USER_NAME = ''
SHOPEE_PASSWORD = ''

#PATH CHROME DRIVER
PATH_CHROME_DRIVER = ''

#CHATGPT ACCOUNT
EMAIL_CHATGPT = ''
PASSWORD_CHATGPT = ''